"""
Django settings for django_s3_app project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Application definition
INSTALLED_APPS = [
    # Django admin removed - using Keycloak for authentication management
    # 'django.contrib.admin',
    # django.contrib.auth is required for Keycloak authentication backend
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'attachments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'keycloak_auth.middleware.KeycloakAuthenticationMiddleware',
]

ROOT_URLCONF = 'django_s3_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_s3_app.wsgi.application'

# Database - DISABLED (No Django database used)
# All data stored in S3 + MongoDB (via external API)
# Uncomment only if you need Django admin or other DB-dependent features
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Dummy database configuration (required by Django even if not used)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'keycloak_auth.drf_authentication.KeycloakAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1:8001',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django_s3_app.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'keycloak_auth': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        's3_service': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB

# =============================================================================
# CUSTOM APPLICATION SETTINGS
# =============================================================================

# AWS S3 Configuration
# IAM User credentials (used to assume role)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')

# IAM Role configuration for S3 access
AWS_ROLE_ARN = config('AWS_ROLE_ARN', default='')
AWS_ROLE_SESSION_NAME = config('AWS_ROLE_SESSION_NAME', default='s3-service-session')
AWS_ROLE_SESSION_DURATION = config('AWS_ROLE_SESSION_DURATION', default=14400, cast=int)  # 4 hours in seconds

# S3 Bucket configuration
AWS_S3_BUCKET_NAME = config('AWS_S3_BUCKET_NAME', default='')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_SSE_ALGORITHM = config('AWS_S3_SSE_ALGORITHM', default='AES256')
AWS_S3_SSE_KMS_KEY_ID = config('AWS_S3_SSE_KMS_KEY_ID', default=None)
AWS_S3_PRESIGNED_URL_EXPIRY = config('AWS_S3_PRESIGNED_URL_EXPIRY', default=3600, cast=int)
AWS_S3_PUBLIC_URL_EXPIRY = config('AWS_S3_PUBLIC_URL_EXPIRY', default=86400, cast=int)
# When True, the S3 client will verify connectivity/credentials by calling head_bucket at init.
# Set to False in CI or when you intentionally want client-side signing without live AWS verification.
AWS_S3_VERIFY_ON_INIT = config('AWS_S3_VERIFY_ON_INIT', default=False, cast=bool)
# If True, a failure to access the configured bucket (HeadBucket AccessDenied/Forbidden)
# will be treated as fatal. If False, credential validity (via STS) is used and lack of
# bucket permissions will only warn and allow startup.
AWS_S3_VERIFY_STRICT = config('AWS_S3_VERIFY_STRICT', default=False, cast=bool)

# Keycloak Configuration
KEYCLOAK_ISSUER = config('KEYCLOAK_ISSUER', default='')


KEYCLOAK_SERVER_URL = config('KEYCLOAK_SERVER_URL', default='')
KEYCLOAK_REALM = config('KEYCLOAK_REALM', default='')
KEYCLOAK_CLIENT_ID = config('KEYCLOAK_CLIENT_ID', default='')
KEYCLOAK_CLIENT_SECRET = config('KEYCLOAK_CLIENT_SECRET', default='')
KEYCLOAK_USER_ROLES = config('KEYCLOAK_USER_ROLES', default='BUY,SEL', cast=Csv())
KEYCLOAK_TOKEN_CACHE_TIMEOUT = config('KEYCLOAK_TOKEN_CACHE_TIMEOUT', default=3600, cast=int)
KEYCLOAK_REQUEST_TIMEOUT = config('KEYCLOAK_REQUEST_TIMEOUT', default=30, cast=int)
KEYCLOAK_JWKS_URI = config('KEYCLOAK_JWKS_URI', default='')
KEYCLOAK_ISSUER = config('KEYCLOAK_ISSUER', default='')
KEYCLOAK_AUDIENCE = config('KEYCLOAK_AUDIENCE', default='')

# API Configuration
API_PREFIX = config('API_PREFIX', default='api/v1/')

# Service Account Configuration for batch/backend operations
KEYCLOAK_SERVICE_ACCOUNT_EMAIL = config('KEYCLOAK_SERVICE_ACCOUNT_EMAIL', default='sb.docadmin@drworkplace.microsoft.com')

# Computed Keycloak URLs
KEYCLOAK_TOKEN_URL = f"{KEYCLOAK_SERVER_URL.rstrip('/')}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token" if KEYCLOAK_SERVER_URL and KEYCLOAK_REALM else ''
KEYCLOAK_ADMIN_URL = f"{KEYCLOAK_SERVER_URL.rstrip('/')}/admin/realms/{KEYCLOAK_REALM}" if KEYCLOAK_SERVER_URL and KEYCLOAK_REALM else ''

# Keycloak issuer and JWKS (for token verification)
# You can set KEYCLOAK_ISSUER explicitly in the env, otherwise it will be computed
KEYCLOAK_ISSUER = config('KEYCLOAK_ISSUER', default=(f"{KEYCLOAK_SERVER_URL.rstrip('/')}/realms/{KEYCLOAK_REALM}" if KEYCLOAK_SERVER_URL and KEYCLOAK_REALM else ''))
# JWKS URI for public keys (override or computed from issuer)
KEYCLOAK_JWKS_URI = config('KEYCLOAK_JWKS_URI', default=(f"{KEYCLOAK_ISSUER}/protocol/openid-connect/certs" if KEYCLOAK_ISSUER else ''))
# Audience to validate in tokens (defaults to client id)
KEYCLOAK_AUDIENCE = config('KEYCLOAK_AUDIENCE', default=KEYCLOAK_CLIENT_ID)

# FastAPI Integration Configuration (was FastPay)
# FASTAPI app base URL used by services that call the FastAPI app
FASTAPI_APP_BASE_URL = config('FASTAPI_APP_BASE_URL', default='')

# Document Orders API Configuration
DOCUMENT_ORDERS_API_BASE_URL = config('DOCUMENT_ORDERS_API_BASE_URL', default='')

# Kafka Configuration for AWS MSK
KAFKA_BOOTSTRAP_SERVERS = config('KAFKA_BOOTSTRAP_SERVERS', default='localhost:9092', cast=Csv())
KAFKA_SECURITY_PROTOCOL = config('KAFKA_SECURITY_PROTOCOL', default='')
KAFKA_SASL_MECHANISM = config('KAFKA_SASL_MECHANISM', default='')
KAFKA_SASL_USERNAME = config('KAFKA_SASL_USERNAME', default='')
KAFKA_SASL_PASSWORD = config('KAFKA_SASL_PASSWORD', default='')